name: my_ecommerce_app

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    restart: always
    networks:
      - my_ecommerce_app

  api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: pujanprajapati/my_ecommerce_app-api
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - my_ecommerce_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: pujanprajapati/my_ecommerce_app-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - my_ecommerce_app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - api

volumes:
  mongo_data:

networks:
  my_ecommerce_app:
    driver: bridge
